security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        GFS\MainBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_CHEF_DEPARTEMENT: ROLE_CHEF_DEPARTEMENT

    providers:
        main_provider:
            entity:
                class: GFSMainBundle:User
                property: username
    firewalls:
        main:
            pattern:    ^/
            anonymous:  true
            provider: main_provider
            form_login:
              login_path: gfs_main_loginpage
              check_path: login_check
            logout:
              path:       logout
              target:     gfs_main_loginpage
    access_control:
        - { path: ^/gestionScolarite, roles: ROLE_ADMIN }
        - { path: ^/gestionScolarite, roles: ROLE_ADMIN }
