<?php

namespace GFS\statistiquesBundle\Repository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllDepartement() {
        $qb = $this->createQueryBuilder('Departement')
            ->select('Departement.id, Departement.nom')
            ->orderBy('Departement.nom')
        ;
        return $qb->getQuery()->getArrayResult();
    }
}
