<?php

namespace GFS\statistiquesBundle\Repository;

/**
 * Etudiant_NiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Etudiant_NiveauRepository extends \Doctrine\ORM\EntityRepository
{
}
