<?php

namespace GFS\statistiquesBundle\Repository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllEtudiantForStat() {
        $sql = 'SELECT e.id,e.ddn as dateNaiss,e.lieunaiss, e.sexe, e.nationalite, n.nom as niveau,
            e.statut, e.paysNaiss,e.cin, e.tel, e.num,e.nature, e.serieBac,e.paysNaiss,
            e.nom as nom, e.prenom,o.nom as nomOption,
            d.nom as nomDepartement, f.nom  as nomFormation, nE.resultat, nE.anneeAcademique
        FROM
            GFSstatistiquesBundle:Etudiant e,
            GFSstatistiquesBundle:Niveau n,
            GFSstatistiquesBundle:NiveauEtudiant nE,
            GFSstatistiquesBundle:Formation f,
            GFSstatistiquesBundle:Departement d,
            GFSstatistiquesBundle:OptionDep o
        where o.departement=d
            and f.optionDep = o
            and e.formation = f
            and nE.etudiant = e
            and nE.niveau = n';
        return $this->getEntityManager()->createQuery($sql)->getResult();

    }
    public function getEtudiant($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT e.id,e.ddn as dateNaiss,e.lieunaiss, e.sexe, e.nationalite, n.nom as niveau,
            e.statut, e.ddn,e.cin, e.tel, e.num,e.nature, e.serieBac,e.paysNaiss,
            e.nom as nom, e.prenom,o.nom as nomOption,
            d.nom as nomDepartement, f.nom  as nomFormation, nE.resultat, nE.anneeAcademique
        FROM
            GFSstatistiquesBundle:Etudiant e,
            GFSstatistiquesBundle:Niveau n,
            GFSstatistiquesBundle:NiveauEtudiant nE,
            GFSstatistiquesBundle:Formation f,
            GFSstatistiquesBundle:Departement d,
            GFSstatistiquesBundle:OptionDep o
        where e.id = :id
            and o.departement = d
            and f.optionDep = o
            and e.formation = f
            and nE.etudiant = e
            and nE.niveau = n ')->setParameter('id',$id);
        return $query->getSingleResult();

    }

}
