<?php

namespace GFS\statistiquesBundle\Repository;

/**
 * NationaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
