<?php

namespace GFS\statistiquesBundle\Repository;

/**
 * NiveauEtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauEtudiantRepository extends \Doctrine\ORM\EntityRepository
{
}
