<?php

namespace Proxies\__CG__\GFS\statistiquesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Etudiant extends \GFS\statistiquesBundle\Entity\Etudiant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'nom', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'prenom', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'ddn', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'lieunaiss', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'paysNaiss', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'cin', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'tel', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'serieBac', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'sexe', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'num', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'nature', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'nationalite', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'statut', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'formation', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'departement', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'option', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'niveau', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'anneeAcademique', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'resultat', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'dateInscrit'];
        }

        return ['__isInitialized__', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'id', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'nom', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'prenom', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'ddn', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'lieunaiss', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'paysNaiss', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'cin', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'tel', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'serieBac', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'sexe', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'num', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'nature', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'nationalite', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'statut', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'formation', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'departement', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'option', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'niveau', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'anneeAcademique', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'resultat', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\Etudiant' . "\0" . 'dateInscrit'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Etudiant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDepartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartement', []);

        return parent::getDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartement($departement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartement', [$departement]);

        return parent::setDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function getOption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOption', []);

        return parent::getOption();
    }

    /**
     * {@inheritDoc}
     */
    public function setOption($option)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOption', [$option]);

        return parent::setOption($option);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau($niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeAcademique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeAcademique', []);

        return parent::getAnneeAcademique();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeAcademique($anneeAcademique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeAcademique', [$anneeAcademique]);

        return parent::setAnneeAcademique($anneeAcademique);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultat', []);

        return parent::getResultat();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultat($resultat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultat', [$resultat]);

        return parent::setResultat($resultat);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInscrit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInscrit', []);

        return parent::getDateInscrit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInscrit($dateInscrit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInscrit', [$dateInscrit]);

        return parent::setDateInscrit($dateInscrit);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDdn($ddn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDdn', [$ddn]);

        return parent::setDdn($ddn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDdn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDdn', []);

        return parent::getDdn();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieunaiss($lieunaiss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieunaiss', [$lieunaiss]);

        return parent::setLieunaiss($lieunaiss);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieunaiss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieunaiss', []);

        return parent::getLieunaiss();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysNaiss($paysNaiss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysNaiss', [$paysNaiss]);

        return parent::setPaysNaiss($paysNaiss);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysNaiss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysNaiss', []);

        return parent::getPaysNaiss();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerieBac($serieBac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerieBac', [$serieBac]);

        return parent::setSerieBac($serieBac);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerieBac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerieBac', []);

        return parent::getSerieBac();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setNum($num)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNum', [$num]);

        return parent::setNum($num);
    }

    /**
     * {@inheritDoc}
     */
    public function getNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNum', []);

        return parent::getNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setNature($nature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNature', [$nature]);

        return parent::setNature($nature);
    }

    /**
     * {@inheritDoc}
     */
    public function getNature()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNature', []);

        return parent::getNature();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalite($nationalite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalite', [$nationalite]);

        return parent::setNationalite($nationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalite', []);

        return parent::getNationalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormation(\GFS\statistiquesBundle\Entity\Formation $formation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormation', [$formation]);

        return parent::setFormation($formation);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormation', []);

        return parent::getFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function getDdnToStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDdnToStr', []);

        return parent::getDdnToStr();
    }

}
