<?php

namespace Proxies\__CG__\GFS\statistiquesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NiveauEtudiant extends \GFS\statistiquesBundle\Entity\NiveauEtudiant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'id', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'resultat', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'anneeAcademique', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'dateInscrit', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'etudiant', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'niveau'];
        }

        return ['__isInitialized__', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'id', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'resultat', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'anneeAcademique', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'dateInscrit', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'etudiant', '' . "\0" . 'GFS\\statistiquesBundle\\Entity\\NiveauEtudiant' . "\0" . 'niveau'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NiveauEtudiant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResultat($resultat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResultat', [$resultat]);

        return parent::setResultat($resultat);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultat', []);

        return parent::getResultat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtudiant(\GFS\statistiquesBundle\Entity\Etudiant $etudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtudiant', [$etudiant]);

        return parent::setEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiant', []);

        return parent::getEtudiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(\GFS\statistiquesBundle\Entity\Niveau $niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeAcademique($anneeAcademique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeAcademique', [$anneeAcademique]);

        return parent::setAnneeAcademique($anneeAcademique);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeAcademique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeAcademique', []);

        return parent::getAnneeAcademique();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInscrit($dateInscrit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInscrit', [$dateInscrit]);

        return parent::setDateInscrit($dateInscrit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInscrit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInscrit', []);

        return parent::getDateInscrit();
    }

}
